---
- name: Data federation services
  hosts: master
  gather_facts: "no"
  vars:
    # Services
    owncloud_hostname: "owncloud"
    
    # Domain
    cloudflare_proxied: "false"
    proxied_suffix: ""
    
    # Logging
    no_sensitive_logging: "false"

  tasks:
    # Data Federation Tool for Kubernetes
    - name: Installing Owncloud
      include_role:
        name: roles/data-federation
      vars:
        # Common vars
        # Generated secrets used by both Kibana, Prometheus and Grafana
        federation_username: "{{federation_username}}"
        federation_password: "{{federation_password}}"
        # Default domain to be used for Ingress hosts
        base_domain: "{{proxied_suffix}}.{{domain}}"
        # For disabling or enabling sensitive logging option
        nologging: "{{no_sensitive_logging}}"
        
        # Logging - EFK stack vars
        owncloud_host: "{{owncloud_hostname}}{{proxied_suffix}}.{{domain}}"
        owncloud_version: "1.0.7"
